---
- name: Deploy 
  hosts: webservers
  sudo: True
  vars:
    projects_dir: /home/ansible/projects
  tasks:
    - git:
        accept_hostkey: True
        dest: /home/ansible/projects/overskya
        force: yes
        update: yes
        repo: https://github.com/kjartab/overskya
